H2PipeInteger: 0
H2CO2Cap: 0
NetworkExpansion: 0
TimeDomainReductionFolder: "TDR_Results"
ModelingToGenerateAlternativeIterations: 3
SystemCO2Constraint: 1
H2G2PCommit: 0
ModelH2Trucks: 0
ParameterScale: 0
H2NetworkExpansion: 0
EnergyShareRequirement: 1
PrintModel: 0
TimeDomainReduction: 0
Trans_Loss_Segments: 1
CapacityReserveMargin: 0
ModelingtoGenerateAlternativeSlack: 0.1
Solver: "Gurobi"
MethodofMorris: 0
ModelH2G2P: 0
LongDurationStorage: 0
ModelH2Liquid: 0
Reserves: 0
StorageLosses: 0
OperationWrapping: 0
OverwriteResults: 0
UCommit: 2
H2GenCommit: 0
ModelingToGenerateAlternatives: 0
MinCapReq: 0
CO2Cap: 0
ModelH2: 1
H2TrucksMaxDistance: 500
WriteShadowPrices: 1
ModelH2Pipelines: 0
