ModelCSC: 1 #Flag to turn or off Carbon Supply Chain modelling capabilities - 0 = no CSC, 1= CSC modeled

ModelCO2Storage: 1 #Model CO2 injection and storage; 0 = not acvtive; 1 = active

CO2PipeInteger: 0 # Whether to model pipeline capacity as discrete or integer 0 = continuous capacity, 1 = discrete capacity
ModelCO2Pipelines: 0 # Whether to model pipeline in CO2 supply chain - 0 = not included, 1 = included
CO2NetworkExpansion: 0 # Transmission network expansional; 0 = not active; 1 = active systemwide
CO2PipeDirection: 1

CO2Pipeline_Loss: 0 #Loss of CO2 from pipelines